version: "3.9"

services:
    elasticsearch:
        image: 117503445/elasticsearch
        container_name: elasticsearch
        restart: unless-stopped
        ports:
        - "9200:9200"
        - "9300:9300"
        volumes:
        - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        # - ./data:/usr/share/elasticsearch/data # ./data should have 777 permission
        environment:
            ES_JAVA_OPTS: "-Xmx256m -Xms256m"
            ELASTICSEARCH_USERNAME: elastic
            ELASTIC_PASSWORD: ${password}
            discovery.type: single-node

    kibana:
        image: docker.elastic.co/kibana/kibana:7.12.0
        container_name: kibana
        restart: unless-stopped
        ports:
            - "5601:5601"
        depends_on:
            - elasticsearch
        volumes:
            - ./kibana.yml:/usr/share/kibana/config/kibana.yml
        environment:
            ELASTICSEARCH_USERNAME: elastic
            ELASTICSEARCH_PASSWORD: ${password}